### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'map') on arraySelector 

### ISSUE THREAD

**Issue by mcarriere** [yann510/ss-search#37]
When we use the arraySelector notation and some results don't have the property, a TypeError: Cannot read properties of undefined (reading 'map') is thrown.

For example if the data is
```         
const data = [
    {
        object: { nestedProperty: "value" },
        array: [{ prop1: "value1", prop2: "value2" }],
    },
    {
        object: { nestedProperty: "value" },
    },
 ]
```

and we have "array[prop2]" in searchableKeys

**Comment by yann510** [comment]
Pull request merged, closing issue
