### ISSUE TITLE
Can't do nested searching

### ISSUE THREAD

**Issue by zaynekomichi** [yann510/ss-search#56]
Trying to access data in an object stored in an array for example
```
const data = [
doc1:{
name:"david",
schedule:[{date:monday},{date:tuesday},{date:Wednesday}]
},
doc2:{
name:"Zayne",
schedule:[{date:monday},{date:tuesday},{date:Wednesday}]
}
]
```
Trying to access the schedules but getting nothing, is nested searching supported?

**Comment by yann510** [comment]
I've added a test to confirm it is possible to do what you are looking for, take a look at this PR for an example :)
https://github.com/yann510/ss-search/pull/57
