### ISSUE TITLE
Improve typing of return type with or without `withScore`

### ISSUE THREAD

**Issue by MHebes** [yann510/ss-search#64]
Currently I have to cast the result of `search` to either a `T[]` or a `{ element: T; score: number; }[]` depending on what I give for `options.withScore`.

In addition, there's the unexpected (to me) behavior that even with `options` as `{ withScore: true }`, you can get a result of `T[]` if your `searchText` is falsey.

I propose two alternatives, one which simply improves types and one which would require a small behavior change but would improve types further:

1. (Non-breaking) Add overload types for the `search` function to narrow the return type in the `withScore: false` case:

```diff
@@ -61,6 +61,8 @@
     return round(1 - remainingTextAfterRemovingSearchWords.length / searchableDataStringWithoutNonWordCharacters.length, 4)
 }

+export function search<T>(elements: T[], searchableKeys: string[], searchText: string, options?: { withScore?: false }): T[]
+export function search<T>(elements: T[], searchableKeys: string[], searchText: string, options: { withScore: boolean }): (T | { element: T, score: number })[]
 export function search<T>(elements: T[], searchableKeys: string[], searchText: string, options: { withScore?: boolean } = {}) {
     if (!searchText) {
         return elements
```

2. (Breaking) Change the behavior of `search` when `!searchText` and `withScore: true` to still return the unfiltered list, but add the score anyways so the type is consistently dependent on `options` instead of `searchText` + `options`:
```diff
@@ -61,8 +61,14 @@
     return round(1 - remainingTextAfterRemovingSearchWords.length / searchableDataStringWithoutNonWordCharacters.length, 4)
 }
 
+export function search<T>(elements: T[], searchableKeys: string[], searchText: string, options: { withScore: true }): { element: T, score: number }[]
+export function search<T>(elements: T[], searchableKeys: string[], searchText: string, options?: { withScore?: false }): T[]
+export function search<T>(elements: T[], searchableKeys: string[], searchText: string, options: { withScore: boolean }): (T | { element: T, score: number })[]
 export function search<T>(elements: T[], searchableKeys: string[], searchText: string, options: { withScore?: boolean } = {}) {
     if (!searchText) {
+        if (options.withScore) {
+            return elements.map((x) => ({ element: x, score: 0 }))
+        }
         return elements
     }
```

-----

Here is a workaround which accomplishes the same things without changing the library:

```ts
function typedSearch<T>(elements: T[], searchableKeys: string[], searchText: string, options: { withScore: true }): { element: T, score: number }[]
function typedSearch<T>(elements: T[], searchableKeys: string[], searchText: string, options?: { withScore?: false }): T[]
function typedSearch<T>(elements: T[], searchableKeys: string[], searchText: string, options: { withScore: boolean }): (T | { element: T, score: number })[]
function typedSearch<T>(elements: T[], searchableKeys: string[], searchText: string, options: { withScore?: boolean } = {}) {
    if (!searchText) {
        if (options.withScore) {
            return elements.map((x) => ({ element: x, score: 0 }))
        }
        return elements
    }
    return search(elements, searchableKeys, searchText, options);
}

// e.g.
type T = { a: string }
const stuff: T[] = [{ a: "1" }, { a: "2" }, { a: "3" }]
const a = typedSearch(stuff, ["a"], "2")        // T[]
const b = typedSearch(stuff, ["a"], "2", {})    // T[]
const c = typedSearch(stuff, ["a"], "2", { withScore: false })  // T[]
const d = typedSearch(stuff, ["a"], "2", { withScore: true })   // { element: T, score: number }[]
const e = typedSearch(stuff, ["a"], "2", { withScore: Math.random() < 0.5 })    // (T | { element: T; score: number; })[]
```

**Comment by yann510** [comment]
Thanks for flagging this typing improvement.

I think we could always return the score, but it could be undefined if you didn't pass the withScore option to keep the library fast if you don't care about the score.
This would provide a consistent result object.

That being said, it might introduce confusion to the end user if the score is always undefined.

I think it would be possible to have a conditional return type based on if the withScore attribute is true or false. 
This might add type maintenance challenges though.

I'd love to get your take on this!

**Comment by yann510** [comment]
@MHebes I fixed the return type using conditional typing. This achieves the expected behaviour without the need for overloads, let me know what you think :)
