### ISSUE TITLE
Implement array value for searching 

### ISSUE THREAD

**Issue by zaynekomichi** [yann510/ss-search#73]
Given we can search using a value (string/number) why not implement multisearch whihc will use an array of search values for example

`
let data = search(users,["name","age","year"],["Zayne","20","2023"])
`

**Comment by yann510** [comment]
Hey,

Why wouldn't you combine your arrays instead of passing them one by one?
This would be supported out of the box by the library without any changes to it.

Let me know what you think ;)

**Comment by zaynekomichi** [comment]
True, ended up having to concatenate the different search options into on string. Works like a charm!

**Comment by yann510** [comment]
Awesome, I'm glad to hear this 😎
